### PR TITLE
SLING-11203: Introduce requireImportProvider directive

### PR DESCRIPTION
**Pull request by enapps-enorman**
A declared requireImportProvider directive or configured defaultRequireImportProviders list so the author can ensure that the
files are processed as intended

This is an attempt an implementation of what I proposed at https://github.com/apache/sling-org-apache-sling-jcr-contentloader/pull/12#issuecomment-1062982927

### CODE REVIEW

**Comment by stefanseifert** [comment]
i can confirm that this PR actually fixes the problem loading composum on my windows environment, same as https://github.com/apache/sling-org-apache-sling-jcr-contentloader/pull/12

what is not so nice with this PR is the "log experience" - although nothing is "wrong" a lot of error messages are logged only due to the delayed startup behavior:
[220310_error.log](https://github.com/apache/sling-org-apache-sling-jcr-contentloader/files/8223524/220310_error.log)

such an error message is important if there is really no fitting content reader present. but it should not be shown only because the reader from the same bundle takes a few microseconds more to load to be ready. this is confusing for anyone monitoring the error log.

**Comment by enapps-enorman** [comment]
@stefanseifert Thanks for confirming that it eventually gets into the right state.  I've made another adjustment that should reduce the log message noise.  Does this resolve your concerns?

You should now get one WARN message (no stacktrace) per bundle the first time it fails and then one INFO message per bundle after the retry logic is successful.

For example:
`[main] WARN org.apache.sling.jcr.contentloader.internal.BundleContentLoader - Cannot load initial content for bundle mock-bundle : Unable to locate a required content reader for entry SLING-INF/libs/app.xml
[main] INFO org.apache.sling.jcr.contentloader.internal.BundleContentLoader - Retrying to load initial content for bundle mock-bundle succeeded.
`

**Comment by stefanseifert** [comment]
this looks much better, thanks.

> I'd like to hear more about 'c)', it seems like you may be saying that you
> want to defer all Content-Loading until all of the configured
> 'defaultRequireImportProviders' are satisfied?  I'm not sure that is better
> than 'b)' since you may encounter a situation where you are waiting for
> something that never arrives and is never used.

yes, i still would prefer combining this with https://github.com/apache/sling-org-apache-sling-jcr-contentloader/pull/12 to get rid if those warnings as well - in case they affect the built-in content readers.

i do not get the point why we should wait without success for one of the 4 built-in content readers when we introduce a hardcoded dependency. they are even the default ones for the directive introduced here, and 99% of all bundles which are already out there will rely on this default config. theoretically they could be moved elsewhere in the future, but in practice they are there and in use - until someone forcefully disables them from outside the bundle.

what's the downside of making those 4 mandatory for the whiteboard to become active?

**Comment by enapps-enorman** [comment]
> what's the downside of making those 4 mandatory for the whiteboard to become active?

I guess the downside would be that as soon as someone disables any of those ContentReader components then no Content-Loading could be done anymore since one of those "mandatory" components would never be activated.  If those disabled ContentReader components are never used anywhere then it should still be able to load stuff that doesn't use that code path.

I can imagine a scenario where some organization has standardized on json as the format for all Content-Loading and has disabled the zip and xml Content-Loaders in their builds.  Perhaps they don't want to leave unused code paths around so they don't have to deal with any future security concerns with xml or zip file parsing code.

**Comment by kwin** [comment]
> as someone disables any of those ContentReader components

You mean via http://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#org.osgi.service.component.runtime.ServiceComponentRuntime.disableComponent-ComponentDescriptionDTO-? That is only supposed to be accessed by AdministrativeBundles and I never experienced such a case. Is it enough if we deal with that once someones runs into issues?

**Comment by enapps-enorman** [comment]
@kwin I was not referring to any specific technique for disabling the component.  I imagine that there could be many ways to get to a state where one of the ContentReader components is not active.  

If the community doesn't want the innocuous log message produced this PR (in some environments) then I don't see much point in trying to merge the concepts from PR #12 and this one.  So just pick one or the other.

**Comment by kwin** [comment]
For me #12 makes sure that by default it waits for all included bundles. This PR allows to wait for other readers (which #12 doesn't tackle at all). Both are useful and should IMHO be combined, because PR #12 doesn't allow to wait for custom readers to be registered.

**Comment by enapps-enorman** [comment]
@kwin But, just 40 minutes ago you stated for another reason that you wanted to "deal with that once someones runs into issues".

Any "wait for custom readers" part doesn't seem to be relevant for solving SLING-11189

**Comment by kwin** [comment]
For me the case that someone disables the default readers is very unlikely but someone using custom readers is much more likely. Therefore I am for combining both approaches

**Comment by enapps-enorman** [comment]
@kwin That is not a convincing argument as to how that part is relevant for solving SLING-11189

**Comment by stefanseifert** [comment]
i've created a new ticket for this proposal: https://issues.apache.org/jira/browse/SLING-11203

**Comment by enapps-enorman** [comment]
closing.  Replaced by PR #15

**Pull request closed without merging**
