### PR TITLE
SLING-11189 ensure all built-in content readers are registered before processing any bundle in this listener

### PR DESCRIPTION
**Pull request by stefanseifert**

### CODE REVIEW

**Review by kwin — APPROVED** [review]
LGTM

**Comment by enapps-enorman** [comment]
Shouldn't the required readers be configurable?  What if I want other readers to be required or want one of those built in readers to be disabled or not required for some reason?  I don't have that requirement at the moment, but this seems to be making assumptions about the intent.

**Comment by stefanseifert** [comment]
we've discussed this in https://issues.apache.org/jira/browse/SLING-11189 and at least for that ticket decided to keep this fix to the built-in content readers.

i currently do not see a use case to disable some of the built-in content readers via OSGi - we already have support to disable readers in the bundle metadata (ignoreImportProviders).

**Comment by enapps-enorman** [comment]
> i currently do not see a use case to disable some of the built-in content readers via OSGi - we already have support to disable readers in the bundle metadata (ignoreImportProviders).

I don't think that is your call to make.  You can't say for certain what other use cases people may need now or in the future.

**Comment by stefanseifert** [comment]
making it configurable would have the benefit that it also supports custom content readers, they could be added to the check via configuration.

**Comment by enapps-enorman** [comment]
Perhaps what is really needed here is the inverse of the ignoreImportProvider directive.  Perhaps a new declared (or implied when missing?) requireImportProvider directive so the author can dictate how the files are intended to be processed.

**Comment by stefanseifert** [comment]
this would probably have been a better design decision initially, but for backward compatibility we have to handle all the existing bundles that expect the built-in providers to be always available. i vote to go with the approach of this PR, but make the list of readers configurable. introducing a new directive for this now makes the always quite complex list of parameters for content loading even more complex.

**Comment by kwin** [comment]
Let us only make it configurable (i.e. more complex) when someone requests it. Currently I also fail to see a use case.

**Comment by kwin** [comment]
The PR as is fixes the issue (with the hardcoded list). I meant a use case for requiring other content readers!

**Comment by enapps-enorman** [comment]
> The PR as is fixes the issue (with the hardcoded list). I meant a use case for requiring other content readers!

Perhaps, but this PR is not backward compatible.  We could fix it quickly, or fix it correctly.

**Comment by jsedding** [comment]
We could also turn the problem around: create the reader instances using their respective constructor within the `ContentReaderWhiteboard` and also register them as services.

**Comment by stefanseifert** [comment]
merging this PR as quick solution for Sling 12 release. discussion about more sustainable solution will continue in https://issues.apache.org/jira/browse/SLING-11203

**Pull request merged**
